cloud_fusion:
  ros__parameters:
    input_topics:
      - /front/cloud
      - /right/cloud
      - /back/cloud
      - /left/cloud

    target_frame: base_link
    publish_topic: /nova/cloud_fused

    voxel_size: 0.05
    max_age_sec: 0.5
    publish_rate_hz: 10.0

    start_type_description_service: true

